Terminé la seccion 9,practica extra seccion 8
CarlosMay7/Curso-Web pull request #6
Opened 2023-04-22 05:40 UTC by CarlosMay7

Terminé una práctica extra en la seccion 8 y terminé la sección 9

2023-04-22 16:55 UTC, jfer1990 commented on seccion-9/contacto.html
Carlos, tienes 2 , h1 en tu página, lo ideal es que tengas 1 únicamente y preferiblemente en la cabecera principal del sitio

2023-04-22 17:00 UTC, jfer1990 requested changes, later dismissed
Carlos, de la práctica 8 súper!, 
De la sección 9 porfa unos cambios:
Corrige el espaciado de la sección donde dice nuestro blog y nuestros cursos y talleres en el index.
Y se la sección de contacto, haz que todos los inputs estén bien alineados, seguramente podrás usar grid ya que lo usaste muy bien en tu práctica 8, El mensaje de texto debe ocupar la misma longitud que los inputs de nombre e email

2023-04-23 03:40 UTC, LUGAMAFE requested changes
Hola carlos un poco mejor solo falta que el text area tenga el mismo tamaño y alineacion que los otros inputs. ya con eso quedaria yo creo.

2023-04-23 23:12 UTC, LUGAMAFE approved these changes

2023-04-23 23:13 UTC, LUGAMAFE approved these changes
Listo!

2023-04-23 23:14 UTC, LUGAMAFE approved these changes

2023-04-24 01:57 UTC, merged